name: test

on:
  push:
    branches:
      - 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: CPU info
        run: |
          cat /proc/cpuinfo
          lscpu

      - name: Run Docker containers
        run: |
          time docker run --rm ubuntu:latest sh -c 'dd if=/dev/urandom of=/dev/null bs=1M count=10000'
